SELECT A1.MACHINE_ID,ROUND(AVG(A1.timestamp-A2.timestamp),3)
AS PROCESSING_TIME
FROM ACTIVITY A1
INNER JOIN ACTIVITY A2 
ON A1.MACHINE_ID=A2.MACHINE_ID
AND A1.PROCESS_ID=A2.PROCESS_ID
AND A1.timestamp>A2.timestamp
GROUP BY A1.MACHINE_ID
